### ISSUE TITLE
Prevent opening a book that is already open

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#103]

**Comment by elsylambert** [comment]
Looks good in v0.0.18 build cc1f350. When user tries to open a book which is already open in a card, then a pop-up is shown at the bottom of screen that the "Book is already open", hence preventing the users to open multiple cards with the same book.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Looks good
