### ISSUE TITLE
Prevent loss of unsaved data

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#107]
After a number of other bug fixes, this one item remains. To replicate:
- Open a book, make a change
- Click away and observe that the save data button is now enabled
- Now close that tab or refresh the page

The changes made are now lost.

The app needs a way to determine if there are unsaved changes and to alert the user.

Suggestion: expose an action from the pk cache context that the app can use to check if any data is unsaved.

**Comment by mandolyte** [comment]
Prompt: reword and make it look nice

Offer three buttons/actions:
1. Save: save the data and close the card
2. Continue closing: close the card without saving (1)
3. Cancel: return to card

(1) for now the continue closing will not lose the changes since the data is cached in the PK Context Provider.

@larsgson @birchamp

**Comment by elsylambert** [comment]
Seeing the Warning Prompt for Unsaved data as below:
<img width="773" alt="Screenshot 2023-02-08 at 3 28 55 PM" src="https://user-images.githubusercontent.com/51806180/217644432-e71c7cc3-497f-4595-883a-0a1398d2d097.png">
 But, when you click on Continue, the other open card gets closed.
- Open gT, Add Ruth and Add Titus.
- Make some edits to Ruth, see that Save button is enabled. DO Not Save yet.
- Close the card by clicking X on the card. You ll see the prompt.
- Click on Continue. Note that it first closes Titus card. 
- Again, Close the card by clicking X on the card. You ll see the prompt again
- Click again on Continue , Now the Ruth Card closes.
Case II:
- Add Ruth card and Add Titus.
- Make some edits to Ruth, see that Save button is enabled. DO Not Save yet.
- Go to Titus Card, make some edits to Ruth, see that Save button is enabled. DO Not Save.
- Click on Ruth card again and make some more changes. Now Close the card without Saving. You ll see the prompt.
- Click on Continue. Note that it first closes Titus card and Titus changes are lost.

**Comment by mandolyte** [comment]
Actually both popups are there. If you move the top one you'll see the other. But we obviously should only show the one for which the user has clicked to close.

Great catch!

**Comment by elsylambert** [comment]
<img width="1492" alt="Screenshot 2023-03-01 at 12 58 56 PM" src="https://user-images.githubusercontent.com/51806180/222223555-7d350615-452a-40a1-899c-281353293cff.png">

**Comment by mandolyte** [comment]
@larsgson here is a video that shows a couple of things that need to be addressed.
[Screen recording 2023-03-06 11.37.54 AM.webm](https://user-images.githubusercontent.com/1289437/223175121-2916e4cf-d122-4deb-95fb-e43c101291f7.webm)

**Comment by elsylambert** [comment]
v0.3.0 build cf4f0aa Edits are not lost. If user closes the card without saving, a warning message appears for the respective card. User can choose to Cancel and save or continue without saving. If user reopens the same book card, edits are still present and Save button is enabled indicating that there are changes in the file that needs to be saved.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Everything looks good
