### ISSUE TITLE
Send feedback in menu does not work

### ISSUE THREAD

**Issue by superdav42** [unfoldingWord/gateway-translate#111]
It always timesout.

**Comment by mandolyte** [comment]
All three gateway apps use the same code. I just tested gateway-edit and -admin and it work in both. So only gateway-translate is having this problem.

**Comment by mandolyte** [comment]
@superdav42 seems to work ok running locally (once you provide the `.env` var values).

I changed the timeout to 10s and it still claims it is timing out. But the console shows this:
![image](https://user-images.githubusercontent.com/1289437/210603885-c0b50cbf-74e5-42e3-9a2b-a272e8d18a9f.png)

So now I am wondering if the problem is the "NonSSRWrapper" that I added early on because of other issues we were having (don't recall them at the moment).

**Comment by superdav42** [comment]
> So now I am wondering if the problem is the "NonSSRWrapper" that I added early on because of other issues we were having (don't recall them at the moment).

I wouldn't expect SSR to be related. It seems when I looked that nothing was setup at /api/feedback to respond to the request. Of course I wouldn't expect it to timeout either. So I don't know.

**Comment by superdav42** [comment]
The root cause of the problem is in v4 of @netlify/plugin-nextjs api function operate very differently from v3. I think all the other apps are using v3 of this plugin and v11 or v10 of nextjs. Since this is a newer repos we set it up with the latest. v4 of the plugin seems to create one function called ___netlify-handler which handles all api requests. V3 creates a function for each endpoint in our case it's called next_api_feedback.  Because of this bug https://github.com/netlify/next-runtime/issues/1174 when using v4 the function timesout  on AWS lambda after 10s while it is starting up before it can serve any requests. 
PR #122 Fixes the problem by downgrading @netlify/plugin-nextjs to v 3.9.2 and and next js to v11.1.4. The app seems to work fine on the older versions so I think we'll keep it this way for now.

To get the latest version working according [to the issue](https://github.com/netlify/next-runtime/issues/1174#issuecomment-1087630605) we will probably need to update all the l rcl's to change the imports as described.

One can see the problem using the netlify-cli and running `netlify serve`. The file at `.netlify/functions/___netlify-handler.zip should be much smaller and not contain all the mui icons and mui code. As it is the file is 27MB but the next_api_feedback.zip with v3 is 600KB. Before the v4 code will work the generated zip will probably need to be less than 1MB.
