### ISSUE TITLE
Cannot type into URL field

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#117]
It loses focus after first character. Works fine if pasting a URL into it. Only direct typing is a problem.

**Comment by elsylambert** [comment]
Not seeing this problem in v0.0.18 build 8d934e9 QA. I am able to type in the URL in the Custom URL field.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Typing in URL isn’t a problem. Working properly
