### ISSUE TITLE
Error evaluating Transform 3 (name=mergePerfText, type=undefined)

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#135]
- Login, select org uW, lang English.
- Open console
- Open Ruth
- Open Titus
- Make a change to Ruth
- Click on the Titus card
- See error in console.

```
Error evaluating Transform 3 (name=mergePerfText, type=undefined): Error max depth of 20 levels exceeded, possible circular reference
```
@superdav42 @larsgson 
Since I had not seen this before, I'm thinking that it may be a condition due to the last two features added to uw-editor:
- the check for unsaved data
- verse scroll sync

**Comment by superdav42** [comment]
I started testing this and it's very inconsistent. I did reproduce it but it took many changes and click back and forth between books to get it to happen. Really not sure why it's happening I'll keep looking.

**Comment by superdav42** [comment]
According to Abel It's a problem in epitelete and epitelete-html and a fix is in dev and waiting to be released.

**Comment by elsylambert** [comment]
Not seeing this issue in v0.1.0 build 7adaf10 QA.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Everything looks good.
