### ISSUE TITLE
Save button is not enabled after undo is done.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-translate#142]
- Open a card, make some changes and Click on Save.
- Close the Card by clicking on X on the top-right of the card.
- Open the same card again, note that the changes from step 1 are there.
- Note that undo button is enabled. Click on Undo button. The changes from step 1 are undone, but the save button  is not enabled.

https://user-images.githubusercontent.com/51806180/222230183-aa02ea0b-f860-4595-bcf9-8b7c86785d7a.mov

- The save button is enabled only after Redo action is activated and the edits are Saved again by Clicking on Save, and then clicking on Undo button.

**Comment by elsylambert** [comment]
Save, undo and Redo functions are working fine when a card is closed and reopened in v0.3.0 build cf4f0aa.

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. Looks like everything is working properly.
