### ISSUE TITLE
Navigation doesn't work with verse spans

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#147]
This could impact whether navigation goes into 0.9 or 1.0.

**Comment by elsylambert** [comment]
Not seeing Navigation bar in v0.3.0 build cf4f0aa. This would be made available in the next Release.
<img width="1765" alt="Screenshot 2023-03-14 at 7 58 12 AM" src="https://user-images.githubusercontent.com/51806180/224994364-135e69bc-cf7f-4590-92fd-f38c24c1034f.png">
