### ISSUE TITLE
Save point is not being recognized

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#151]
Steps:
- open Ruth
- make a change
- save it
- now click undo
- observe that save button is *not* enabled even tho a change is made after the point of saving

[Screen recording 2023-03-11 9.14.01 AM.webm](https://user-images.githubusercontent.com/1289437/224489660-d5cd5324-cb5c-401e-865e-893fe1f780b6.webm)

**Comment by elsylambert** [comment]
Will test after @larsgson merges his next set of changes.

**Comment by mandolyte** [comment]
[Screen recording 2023-03-16 9.02.12 AM.webm](https://user-images.githubusercontent.com/1289437/225625849-d0c32601-60d2-48d0-a666-3386cae1d174.webm)

Found a case where it happens again...

**Comment by elsylambert** [comment]
The save button enables correctly upon editing and upon Undo/Redo actions if the state of the text is changed. Looks good to me in v0.9.0-rc.2 build 29a2450.
