### ISSUE TITLE
Disable bible-reference-rcl and card syncing for v0.9

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#152]
The feature should only sync like-named books (as indicated by the book selection). It should *not* sync all cards.

For example, suppose the user has opened both ULT and UST for Ruth, but also 1 Kings.

- if the user selects Ruth 2:2, then both ULT/UST for Ruth should sync to that chapter verse. But 1KI should not move at all.

**Comment by elsylambert** [comment]
Navigation Bar is disabled for 0.9 and not seeing it in latest develop.
<img width="1765" alt="Screenshot 2023-03-14 at 7 58 12 AM" src="https://user-images.githubusercontent.com/51806180/224995213-e5d61573-e2a6-4c05-b25b-886a7ce0d43f.png">
