### ISSUE TITLE
Not showing chapter in chapter sequence for en_ust-unfoldingWord

### ISSUE THREAD

**Issue by danielklapp** [unfoldingWord/gateway-translate#162]
@mandolyte I came across in the book of Psalms (en_ust-unfoldingWord) chapter 73 is missing in the chapter sequence. When you click on chapter 72 it displays both 72 and 73. v0.9.0-rc.1 build f83d6d3 QA 
![Screenshot 2023-03-22 at 8.53.44 PM.png](https://images.zenhubusercontent.com/63e2b3aebe65b0eb5b78a45f/6bbfa41b-d479-4dee-ba01-5cdb2c1314a3)
![Screenshot 2023-03-22 at 8.55.02 PM.png](https://images.zenhubusercontent.com/63e2b3aebe65b0eb5b78a45f/64fe48c7-fd12-4d4c-9943-c657ad3f0659)

**Comment by danielklapp** [comment]
@mandolyte when using development server with v0.2.0 build 78c864f QA the issue was still there. For production server with v0.2.0 build 78c864f the issue was fixed. The issue was fixed for production but not development side.  Here’s a screenshot 

<img width="1437" alt="Screenshot 2023-03-27 at 12 31 07 PM" src="https://user-images.githubusercontent.com/82067076/228007109-b27f6adc-47b9-4358-be08-f3b1b08776d0.png">

**Comment by elsylambert** [comment]
Works in Production.
