### ISSUE TITLE
Successor to uw-editor

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#168]
This is the repo:

https://github.com/unfoldingWord/html-usfm

**Comment by elsylambert** [comment]
uW-editor works as expected in v0.9.2 build 1cb91f9 QA. Seeing blue color on the icon when enabled which looks good. Undo/Redo and Save are working fine. Broken Alignment indicator works fine.

**Comment by danielklapp** [comment]
uW-editor working properly with v0.9.2 build 1cb91f9 QA. Buttons are functioning correctly. I also think the icon color changing to blue when they’re enabled looks good. The broken alignment shows you what’s been broken and where.
