### ISSUE TITLE
Book by URL will open a different card for same URL

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#172]
If you fetch a book by using a URL, for example:
https://qa.door43.org/unfoldingWord/fr_ulb/src/branch/master/57-TIT.usfm

Then close the card, then re-open, it will fetch it again instead of using the instance previously obtained.

**Comment by elsylambert** [comment]
Not seeing this issue in v0.9.2 build 1cb91f9 QA. When a book is opened by URL the second time, the message pop-up is shown "Book is already open".
