### ISSUE TITLE
Change branch name for compatibility with other tools

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#175]
When a DCS branch is created it should be in the form `auto-<user>-<BOOKID>`

**Comment by danielklapp** [comment]
Looks good with v0.9.1 build 60abe7a QA.

**Comment by elsylambert** [comment]
Branch name is now been created as auto-username-bookid. Looks good and works fine in v0.9.2 build 1cb91f9 QA. Edits are saved correctly on the new userbranch.
Note: we should be sure that if anyone has used the v0.9.x beta and wants to keep the changes, they need to save to master before we cut over.
