### ISSUE TITLE
Bible Reference navigation, incl. with click in editor pane

### ISSUE THREAD

**Issue by larsgson** [unfoldingWord/gateway-translate#194]
Chapter and verse navigation syncing both from Bible Reference navigation UI in the app bar, as well as when clicking inside the editor pane (detecting which verse is currently active)
If the same Bible book is opened in another editor pane, then the corresponding verse automatically becomes visible there.

**Comment by larsgson** [comment]
This is solved by PR 191

**Comment by danielklapp** [comment]
The Bible Reference navigation UI is working properly when having same books opened in editor panes (ULT/UST). Wether using top navigation bar, editing a verse, or opening a new chapter and clicking on desired verse to edit, both panes are syncing to one another. Looks good in v1.0.0 build 79e998c QA.

<img width="1435" alt="Screenshot 2023-09-13 at 11 52 11 AM" src="https://github.com/unfoldingWord/gateway-translate/assets/82067076/04dd7347-2d70-4d34-8979-e42cba2b80db">
