### ISSUE TITLE
Add Book, chapter, verse navigation

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#20]
Users need to be able to navigate to books **that have already been added manually**, chapters and verses . See the epic for the mockup #16

All cards of the same book get updated. For now we will **not** implement the link button. 

DoD
---
users can navigate to Book, chapter, and verse using a top navigation bar

**Comment by larsgson** [comment]
Chapter and verse navigation is now working, both from the UI in the app bar and from clicking in editor panes with the same Bible book (i.e. minimum two same Bible book need to be simultaneously open)

**Comment by larsgson** [comment]
I have created a new issue for the Book navigation not yet working - Issue #195

**Comment by elsylambert** [comment]
v0.9.2 build 20f186f on https://develop--gateway-translate.netlify.app/
Unable to open books in a second card. First card opens up fine and loads correctly but after that if user opens up another Book card, it shows errors on the console and the card stays blank.
<img width="1671" alt="Screenshot 2023-08-30 at 11 54 49 AM" src="https://github.com/unfoldingWord/gateway-translate/assets/51806180/566aa4bb-b4ff-42f8-a6fd-d9983991236d">

**Comment by elsylambert** [comment]
v1.0.0 build 79e998c QA. Looks good. Not seeing blank cards on opening the second or third card.
Chapter and verse Navigation works fine.
@larsgson When we navigate to a verse, the verse number used to show in red for users to easily see. I am wondering if that has been changed?

**Comment by danielklapp** [comment]
Agree that there isn’t blank editor panes when opening a second or third pane and that chapter and verse navigation works properly. Tested with v1.0.0 build 79e998c QA.
