### ISSUE TITLE
Page margin is not uniform for all pages

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-translate#215]
In gT, the default page margin is not uniform for all pages when Previewed.

<img width="958" alt="Screenshot 2023-12-19 at 9 03 02 AM" src="https://github.com/unfoldingWord/gateway-translate/assets/51806180/1bca55e8-50b8-4049-a11e-03b8be33e4a3">

<img width="958" alt="Screenshot 2023-12-19 at 9 04 18 AM" src="https://github.com/unfoldingWord/gateway-translate/assets/51806180/88b398d6-7154-4b84-8bbd-65c11fde19bf">

**Comment by larsgson** [comment]
This is intentional and by default odd and even pages are formatted in order to make sense for printing books.
In the future I would suggest to make the "book formatting" optional by selecting / deselecting an option before the actual rendering, but for now it makes sense to keep it like this.

**Comment by elsylambert** [comment]
Closing this issue based on Lar's comment above.
