### ISSUE TITLE
Make card/bookId unique for URL fetches

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/gateway-translate#50]
At present, the ID seems to be upper case bookId followed by the word custom. But:
- how is the bookId determined? inspection of URL is not likely to be reliable
- the word custom works for one such fetch, but what about two of them?

**Comment by larsgson** [comment]
I would propose to use Proskomma for this and to get this information (if available) from inside the document
- I can add the "catalog" information and make this available after the hook "usePkImport" has been called (i.e. updating this code in uw-editor)
- whenever this information is missing inside the Usfm, then we would have to infer from the URL - or as a last resort, use random letters (@mandolyte: is this what is currently done?)

**Comment by elsylambert** [comment]
The title now shows Book name and the URL.
<img width="663" alt="Screenshot 2022-11-09 at 4 14 33 PM" src="https://user-images.githubusercontent.com/51806180/200943268-078aad98-fbac-48c8-9fe9-0a046372e76b.png">
