### ISSUE TITLE
Errors on the console when adding book card through URL

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/gateway-translate#69]
1. Added Book Gen-Literal. Looks fine.
2. Added Book Gen-Simplified. Looks fine.
3. Added Book Gen using this URL: https://qa.door43.org/unfoldingWord/en_ult/src/branch/master/01-GEN.usfm
The card shows loading at first and then shows blank with errors in the console.
![Screenshot 2022-11-08 at 9.08.42 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0735ef8d-6971-47ed-b4d0-5982a92f128d)

**Comment by elsylambert** [comment]
@mandolyte The URL above ^^ was not the raw file. When I added the raw USFM, https://qa.door43.org/unfoldingWord/en_ult/raw/branch/master/01-GEN.usfm it works. Can there be an indication to the user that the URL is not correct or in the right format?

**Comment by superdav42** [comment]
> @mandolyte The URL above ^^ was not the raw file. When I added the raw USFM, https://qa.door43.org/unfoldingWord/en_ult/raw/branch/master/01-GEN.usfm it works. Can there be an indication to the user that the URL is not correct or in the right format?

This was fixed in https://github.com/unfoldingWord/gateway-translate/pull/68

**Comment by elsylambert** [comment]
Looks good in v0.0.14 build 7323d6c QA. Now able to add USFM without opening the raw file, both format works. Invalid URLs open a blank card with a error message indicating to the user that they have entered a invalid USFM.
