### ISSUE TITLE
Not able to close the cards 

### ISSUE THREAD

**Issue by Joel-C-Johnson** [unfoldingWord/gateway-translate#77]
In some cases, the cards that are opened are not able to close using the "x" icon

Steps:
1. Open the app and log in
2. Add/Open more than 6 different books in the window.
3. Try to open one or two same books that are opened. 
4. Close the card from the last.
5. You may not close the cards.
Also, the layout is changed. 
![card](https://user-images.githubusercontent.com/25791348/201092435-93e07aba-50e3-47db-aeb7-b9a2f4b6a99f.png)

**Comment by elsylambert** [comment]
Not seeing this problem in v0.0.18 build cc1f350.

**Comment by Joel-C-Johnson** [comment]
> @Joel-C-Johnson Please retest - I think this is now fixed with latest bug fixes

Sorry for the late reply. I tested it, works well. I noticed one thing that shows a pop-up menu(book is already open) if we try to open the same book again. Great work.

**Comment by elsylambert** [comment]
Looks good in v0.9.0-rc.2 build 29a2450.
