### ISSUE TITLE
Breakout notification of broken alignments

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-translate#93]
Broken alignment notification UI needs to be separated from search and replace.  This is a tech debt issue.

**Comment by elsylambert** [comment]
Notifications of Broken alignments look good in v0.0.18 build cc1f350 QA.
<img width="590" alt="Screenshot 2023-01-03 at 9 04 41 AM" src="https://user-images.githubusercontent.com/51806180/210372708-f6ab8c38-68e4-4a9f-a9a1-6ff6ac4e6954.png">

**Comment by danielklapp** [comment]
Tested with v0.9.0-rc.2 build 29a2450 QA. looks good
